DROP DATABASE IF EXISTS userData;
CREATE DATABASE userData;
USE userData;

CREATE TABLE users
(
	userID INT(11) PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(50) NOT NULL,
    pw VARCHAR(50) NOT NULL
);

CREATE TABLE histories
(
	id INT(11) PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    input VARCHAR(50) NOT NULL
);
